export const mockTransactions = [
  {
    id: 1,
    name: "Herbert C. Patton",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    status: "Confirm",
    statusColor: "#10b981",
    amount: "$14,584",
    date: "5/12/2016",
  },
  {
    id: 2,
    name: "Mathias N. Klausen",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    status: "Waiting payment",
    statusColor: "#f59e0b",
    amount: "$8,541",
    date: "10/11/2016",
  },
  {
    id: 3,
    name: "Nikolaj S. Henriksen",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    status: "Confirm",
    statusColor: "#10b981",
    amount: "$954",
    date: "8/11/2016",
  },
  {
    id: 4,
    name: "Lasse C. Overgaard",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    status: "Payment expired",
    statusColor: "#ef4444",
    amount: "$44,584",
    date: "7/11/2016",
  },
  {
    id: 5,
    name: "Kasper S. Jessen",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    status: "Confirm",
    statusColor: "#10b981",
    amount: "$8,844",
    date: "1/11/2016",
  },
];

export const mockOrders = [
  {
    id: "#12354781",
    name: "Riverston Glass Chair",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    status: "Delivered",
    statusColor: "#10b981",
    amount: "$185",
    date: "5/12/2016",
  },
  {
    id: "#52140300",
    name: "Shine Company Catalina",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    status: "Delivered",
    statusColor: "#10b981",
    amount: "$1,024",
    date: "5/12/2016",
  },
  {
    id: "#96254137",
    name: "Trex Outdoor Furniture Cape",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    status: "Cancel",
    statusColor: "#ef4444",
    amount: "$657",
    date: "5/12/2016",
  },
  {
    id: "#12365474",
    name: "Oasis Bathroom Teak Corner",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
    status: "Shipped",
    statusColor: "#f59e0b",
    amount: "$8451",
    date: "5/12/2016",
  },
  {
    id: "#85214796",
    name: "BeoPlay Speaker",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    status: "Delivered",
    statusColor: "#10b981",
    amount: "$584",
    date: "5/12/2016",
  },
  {
    id: "#12354781",
    name: "Riverston Glass Chair",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    status: "Delivered",
    statusColor: "#10b981",
    amount: "$185",
    date: "5/12/2016",
  },
];
